### ISSUE TITLE
Does GSA sharepoint 4 support MOSS 2007?

### ISSUE THREAD

**Issue by bdalal** [googlegsa/sharepoint#3]

**Comment by wiarlawd** [comment]
The version 4.0.0 connector was tested and supported with MOSS 2007. Later versions were not tested with MOSS 2007, and incompatible changes were made in version 4.0.4. Google no longer supports connector versions prior to 4.1.0 with the Google Search Appliance.

**Comment by bdalal** [comment]
Thanks. I have downloaded the 4.0.0 connector from the releases, but am unable to find documentation for it. This link => https://support.google.com/gsa/topic/2721859?hl=en&ref_topic=2707841 provides documentation for 3.0 and 4.0.2 and up. Will this also work for 4.0.0? Else please suggest where I can find the documentation for 4.0.0

**Comment by wiarlawd** [comment]
I need to correct myself on one point. The 4.0 connector was beta, and never supported.

As far as I can tell there was no public doc prior to 4.0.2. The 3.0 doc is for a completely different code base. I would suggest that you are likely better off starting with the 4.0.2 release or even 4.0.3, rather than 4.0.0. In any case, we won't be able to provide much help.
